version: '3'
volumes:
  postgres-db:
    driver: local
services:
  maria:
    container_name: maria
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MYSQL_DATABASE: test
      MYSQL_USER: compose
      MYSQL_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "3306:3306"
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-RTM-ubuntu-20.04
    platform: linux/amd64
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  postgres:
    container_name: postgres
    # FIXME: brittle tests fail with latest PostgreSQL
    image: postgres:14
    environment:
      POSTGRES_USER: compose
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
